### ISSUE TITLE
No module configuration_llama

### ISSUE THREAD

**Issue by wherejumpout** [447428054/stanford_alpaca_llama#1]
I've found this repo to resolve  this problem.
 https://github.com/tatsu-lab/stanford_alpaca/issues/115

When I ran the train.py, an Error raised:

File "/home/tao.peng/github/stanford_alpaca_llama-master/modeling_llama.py", line 33, in <module>
    from configuration_llama import LlamaConfig
ModuleNotFoundError: No module named 'configuration_llama'

Since this repo is really new , is this file missed during the inital commint? 

@447428054

**Comment by 447428054** [comment]
> I've found this repo to resolve this problem. [tatsu-lab/stanford_alpaca#115](https://github.com/tatsu-lab/stanford_alpaca/issues/115)
> 
> When I ran the train.py, an Error raised:
> 
> File "/home/tao.peng/github/stanford_alpaca_llama-master/modeling_llama.py", line 33, in from configuration_llama import LlamaConfig ModuleNotFoundError: No module named 'configuration_llama'
> 
> Since this repo is really new , is this file missed during the inital commint?
> 
> @447428054

yeah,done.

**Comment by wherejumpout** [comment]
cool，it works
thank you
